version: '3'

volumes:
  ano:
    driver: local

networks:
  bridge:
    external:
      name: bridge

services:
  example-apps:
    build: .
    # image: "archlinux:latest"
    container_name: example-container
    entrypoint: "/app/start.sh"
    networks:
      - bridge
    volumes:
      - ano:/app:rw