version: '3'

volumes:
  ano:
    driver: local

networks:
  default:
    mynet:
      external: true

services:
  example-apps:
    build: Dockerfile
    image: "archlinux:latest"
    container_name: example-container
    entrypoint: "/app/start.sh"
    networks:
      - mynet
    volumes:
      - ano:/app:rw