version: '3'

volumes:
  ano:
    driver: local

services:
  example-apps:
    image: "archlinux:latest"
    container_name: example-container
    command: echo "Hello Worlds"
    volumes:
      - ano:/app:rw